# Generated by Django 5.2.7 on 2025-11-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleproducto',
            name='dimensiones',
            field=models.CharField(blank=True, help_text='Resolución de la interfaz del plugin, ej: 1200x800 px.', max_length=100),
        ),
    ]
